<a href="https://colab.research.google.com/github/Sumuk2208/Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. Pytorch fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


##Tensors

scalars

In [3]:
scalar=torch.tensor(3)
scalar.item()

3

In [4]:
#vectors
vec=torch.tensor([1,2])
vec

tensor([1, 2])

In [5]:
#MATRIX
mat=torch.tensor([[1,2],[3,4]])
mat[:1]

tensor([[1, 2]])

In [6]:
#Tensor
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

Random tensor

In [7]:
random_tensor=torch.rand(3,3,2)
random_tensor

tensor([[[0.0184, 0.2561],
         [0.4396, 0.9847],
         [0.7892, 0.8749]],

        [[0.3495, 0.2406],
         [0.1977, 0.9340],
         [0.4141, 0.6145]],

        [[0.3437, 0.3839],
         [0.7211, 0.1755],
         [0.0525, 0.5766]]])

In [8]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeroes/Ones

In [15]:
zeroes=torch.zeros_like(random_tensor, dtype=torch.int32)
zeroes

tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]], dtype=torch.int32)

###Range and tensors like

In [19]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

###dtypes

In [22]:
tensor=torch.tensor([1,2,3], dtype=torch.float32,device=None,requires_grad=False)
tensor.dtype

torch.float32

###Extracting information from tensors
1.device

2.shape

3.dtype


In [27]:
tensor=torch.rand(3,3)
tensor.device,tensor.shape,tensor.dtype

(device(type='cpu'), torch.Size([3, 3]), torch.float32)

###Operations on tensors

In [35]:
tensor1=torch.tensor([1,2,3])
tensor1+10
torch.mul(tensor1,10)


tensor([10, 20, 30])

##Reshaping, stacking, squeezing
* View - return view of the tensor (Shares memory with the input)
* Vstack, hstack
* squeeze- removes all `1` dimensions
* permute- returns view of input permuted in a certain way

In [36]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [38]:
#reshape
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [40]:
#change the view
z=x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))