<a href="https://colab.research.google.com/github/Sumuk2208/Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. Pytorch fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


##Tensors

scalars

In [ ]:
scalar=torch.tensor(3)
scalar.item()

3

In [ ]:
#vectors
vec=torch.tensor([1,2])
vec

tensor([1, 2])

In [ ]:
#MATRIX
mat=torch.tensor([[1,2],[3,4]])
mat[:1]

tensor([[1, 2]])

In [ ]:
#Tensor
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])