<a href="https://colab.research.google.com/github/Sumuk2208/Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. Pytorch fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


##Tensors

scalars

In [3]:
scalar=torch.tensor(3)
scalar.item()

3

In [4]:
#vectors
vec=torch.tensor([1,2])
vec

tensor([1, 2])

In [5]:
#MATRIX
mat=torch.tensor([[1,2],[3,4]])
mat[:1]

tensor([[1, 2]])

In [6]:
#Tensor
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

Random tensor

In [7]:
random_tensor=torch.rand(3,3,2)
random_tensor

tensor([[[0.0184, 0.2561],
         [0.4396, 0.9847],
         [0.7892, 0.8749]],

        [[0.3495, 0.2406],
         [0.1977, 0.9340],
         [0.4141, 0.6145]],

        [[0.3437, 0.3839],
         [0.7211, 0.1755],
         [0.0525, 0.5766]]])

In [8]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)